### ISSUE TITLE
Crash on startup on Pixel 8 with Andorid 14 device

### ISSUE THREAD

**Issue by yamin8000** [yamin8000/freeDictionaryApp#133]

**Comment by martixy** [comment]
It also crashes on my Lineage18 (Android 11) device.

**Comment by yamin8000** [comment]
> It also crashes on my Lineage18 (Android 11) device.

I think the problem is fixed. Please check the new version.
https://github.com/yamin8000/freeDictionaryApp/releases/tag/1.6.5
