### ISSUE TITLE
[feature request] open definition as an overlay

### ISSUE THREAD

**Issue by Cris-Edmundson** [yamin8000/freeDictionaryApp#137]
I'd love the option to show the definition of a word as an overlay when I search a word from outside the app via a context menu, that way I don't leave the app I'm using and can easily get the definition and go back to what I was doing

Like a half height window that opens from the bottom of the screen, and you can close it by tapping on the app behind it on the upper half of the screen

Thanks for y'alls work on the app, its very handy :)

**Comment by yamin8000** [comment]
https://developer.android.com/develop/ui/views/notifications/bubbles

**Comment by yamin8000** [comment]
https://developer.android.com/reference/android/Manifest.permission#SYSTEM_ALERT_WINDOW

**Comment by yamin8000** [comment]
https://developer.android.com/guide/topics/large-screens/multi-window-support

**Comment by yamin8000** [comment]
> Hey, you can have a look at how this kind of popup is implemented in TranslateYou here: https://github.com/you-apps/TranslateYou/pull/429/files.

Thank you. I'll look into it.

**Comment by yamin8000** [comment]
@Cris-Edmundson @Bnyro @nvllz https://github.com/yamin8000/freeDictionaryApp/releases/tag/1.7.1
