### ISSUE TITLE
Feature request: avoid using Google's DNS servers

### ISSUE THREAD

**Issue by j-lakeman** [yamin8000/freeDictionaryApp#181]
It seems the app is using Google's DNS servers (8.8.8.8 and 8.8.4.4). Is that necessary? It's not quite respecting privacy IMHO. Great app apart from this!

**Comment by yamin8000** [comment]
> It seems the app is using Google's DNS servers (8.8.8.8 and 8.8.4.4). Is that necessary? It's not quite respecting privacy IMHO. Great app apart from this!

Yes, this app uses Google's DNS servers and even [other DNS servers](https://github.com/yamin8000/freeDictionaryApp/blob/f8bbf97c3fec9208ef4920e76d40a9ae3dee1827/feature_home/src/main/java/io/github/yamin8000/owl/feature_home/ui/HomeViewModel.kt#L111) too. I found that one of the best and fastest ways to check whether a device is connected to the internet in Android is by [pinging a reliable DNS server](https://stackoverflow.com/a/27312494/15055605). The other way is using the `ConnectivityManager` class in Android which requires an additional permission `android.permission.ACCESS_NETWORK_STATE`.  

I'm happy to use any other way to check for an internet connection if you have any suggestions. As far as I know, I don't think using Google's DNS servers or any other for checking an internet connection violates users' privacy. This app as it is already depends on a certain instance of a network service and I'm not hiding it. If you block any Google's services and/or their DNS servers, even then the app doesn't stop you from searching it only shows a message that you don't have an internet connection. I think [a mere ping request](https://github.com/yamin8000/freeDictionaryApp/blob/f8bbf97c3fec9208ef4920e76d40a9ae3dee1827/feature_home/src/main/java/io/github/yamin8000/owl/feature_home/ui/HomeViewModel.kt#L183) only results in Google knowing your IP which even that can be a NAT-shared IP so the only concern is if you have a static IP. I understand your concern, for now, I keep this issue open for a while to know if it's a wider concern or not.
