### ISSUE TITLE
Copy

### ISSUE THREAD

**Issue by smaragdus** [yamin8000/freeDictionaryApp#27]
When a long press is executed on a word (for example, a synonym) the word is being copied to clipboard automatically (that is right), but also an additional command- **Copy** box, appears on screen:

![Screenshot_20231006-131844](https://github.com/yamin8000/freeDictionaryApp/assets/9025757/d81ebfce-e094-4263-9b22-fa6063859494)

which is redundant and cannot be cleared via **Back** button, so the **Copy** button should be pressed to remove it from screen.

Since on long press the selected word is automatically copied to clipboard (confirmed by **Text copied.** pop-up) there should not appear additional **Copy** command on screen, it is just useless.

I would appreciate an option (check box in **Settings**) to navigate to the selected word on short press in stead of triggering **Text-to-Speech** command.

I also think that it is useless to open the word **free** any time the app starts, loading a blank page with just a **Search** box would be better.

**Comment by yamin8000** [comment]
> When a long press is executed on a word (for example, a synonym) the word is being copied to clipboard automatically (that is right), but also an additional command- **Copy** box, appears on screen:
> which is redundant and cannot be cleared via **Back** button, so the **Copy** button should be pressed to remove it from screen.

You see, that's intended behavior. I agree it's not the best method but the problem is someone maybe want to copy the whole text (long press) and someone maybe wants to select a portion of text then click on copy button to copy that portion that option should be available too.

> Since on long press the selected word is automatically copied to clipboard (confirmed by **Text copied.** pop-up) there should not appear additional **Copy** command on screen, it is just useless.
> 
> I would appreciate an option (check box in **Settings**) to navigate to the selected word on short press in stead of triggering **Text-to-Speech** command.

You can search for any work on the text by double touching and selecting your word, a modal list of words would appear for you.

> I also think that it is useless to open the word **free** any time the app starts, loading a blank page with just a **Search** box would be better.

I think not, I want to emphasize on app being free, however, I can add an option in the settings to opening blank page in the startup instead of searching for the word `free`.

**Comment by smaragdus** [comment]
@yamin8000 

Very quick response, thanks.

What about **Back** button clearing **Copy** box? 

> You can search for any work on the text by double touching and selecting your word, a modal list of words would appear for you.

Thanks for the tip, I did not know that.

What about an option to disable **Text-to-Speech** in **Settings**? I do not need it but often acrivate it by mistake.

Off-topic: Do you plan to add your app to **F-Droid**? And what online dictionary does your app use as back-end?

Regards

**Comment by yamin8000** [comment]
> @yamin8000
> 
> Very quick response, thanks.
> 
> What about **Back** button clearing **Copy** box?

I have to work on that, I don't know if it's possible or not.
> 
> > You can search for any work on the text by double touching and selecting your word, a modal list of words would appear for you.
> 
> Thanks for the tip, I did not know that.
> 
> What about an option to disable **Text-to-Speech** in **Settings**? I do not need it but often acrivate it by mistake.

That's doable, I'll think about it.
> 
> Off-topic: Do you plan to add your app to **F-Droid**? And what online dictionary does your app use as back-end?
> 

Well, I've already done that. It's been a week since I put on the request for my app [submission](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13759) and everything is in order but someone just has to merge my pull request. 
I'm using https://dictionaryapi.dev.
> Regards

**Comment by smaragdus** [comment]
Thanks for the new version ([1.5.0](https://github.com/yamin8000/freeDictionaryApp/releases/tag/1.5.0)) and the blank search screen, you are very fast!

However I encountered another problem. How to reproduce the issue, example:

- search for the word **limn**:
- double click the synonum **illuminate**;
- an error message appears- **No definition for the word found.**
- open history and see that instead of **illuminate**, the app has searched for **illuminate,**, with trailing comma (**,**);

**Screen**:

![Screenshot_20231007-173204](https://github.com/yamin8000/freeDictionaryApp/assets/9025757/42c29906-f31c-4413-9458-ce968180ef1b)


This problem seems to appear randomly on some words. Can you confirm it?

**Comment by yamin8000** [comment]
> Thanks for the new version ([1.5.0](https://github.com/yamin8000/freeDictionaryApp/releases/tag/1.5.0)) and the blank search screen, you are very fast!

Thank you.
> 
> However I encountered another problem. How to reproduce the issue, example:
> 
>     * search for the word **limn**:
> 
>     * double click the synonum **illuminate**;
> 
>     * an error message appears- **No definition for the word found.**
> 
>     * open history and see that instead of **illuminate**, the app has searched for **illuminate,**, with trailing comma (**,**);
> 
> 
> **Screen**:
> 
> 
> This problem seems to appear randomly on some words. Can you confirm it?

I confirm. it does happen. Somewhere I'm not probably sanitizing words extracted from texts. (extra characters like `,` and white spaces should be removed)  
I should create a new issue for it.
