### ISSUE TITLE
Material icons. 

### ISSUE THREAD

**Issue by mischiefCloud** [yamin8000/freeDictionaryApp#48]
Could you please add in material you icons 💜 thankyouuu.

**Comment by yamin8000** [comment]
> material you icons

What do you mean exactly?  
This app already uses Material Icons from Google. I don't think there's any specific Material You Icons.

**Comment by mischiefCloud** [comment]
![Screenshot_20231217-212736](https://github.com/yamin8000/freeDictionaryApp/assets/152065885/d9954fc6-0748-4826-a233-ced7cda75c29)

The app doesn't match themes when enabled. Which sadly makes me have to stop using apps that don't support it. So I'm hoping you can make the relevant changes. 

Thankyou for taking the time to review this issue, I know it's not a priority for most people. But for me it is. 💜

**Comment by yamin8000** [comment]
> ![Screenshot_20231217-212736](https://private-user-images.githubusercontent.com/152065885/291057184-d9954fc6-0748-4826-a233-ced7cda75c29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4MTQyOTQsIm5iZiI6MTcwMjgxMzk5NCwicGF0aCI6Ii8xNTIwNjU4ODUvMjkxMDU3MTg0LWQ5OTU0ZmM2LTA3NDgtNDgyNi1hMjMzLWNlZDdjZGE3NWMyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxN1QxMTUzMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05M2M2ZTE2MmJmMjg2MWMxMmVkYmNlOGJmNjRkZWIzYmU0OGJmMzA3MThmYzRlMDY2ZjI2ODUzYzJhNGE0NDRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Dqwvonc5rlSKujC7rl0qRLuCrJy876Nt5UhZZVFEolE)
> 
> The app doesn't use material you themes when the user has them enabled. Which sadly makes me have to stop using apps that don't support it. So I'm hoping you can make the relevant changes.
> 
> Thankyou for taking the time to review this issue, I know it's not a priority for most people. But for me it is. 💜

Ok, I understand.
That's called a themed app icon or adaptive icon.  
Yeah, I'll do it.

**Comment by mischiefCloud** [comment]
Thankyou so much, great work with the app btw, it's visually stunning.  💜

**Comment by yamin8000** [comment]
> Thankyou so much, great work with the app btw, it's visually stunning. 💜

Well, my phone's launcher doesn't support the Material You Icon pack so I can't test the new feature.  
What's your launcher?

**Comment by yamin8000** [comment]
> Thankyou so much, great work with the app btw, it's visually stunning. 💜

Please test [the last version](https://github.com/yamin8000/freeDictionaryApp/releases/tag/1.5.5).

**Comment by mischiefCloud** [comment]
It is working, great job. Jooks so much better on my phone, I appreciate it so much 💜

**Comment by mischiefCloud** [comment]
![Uploading Screenshot_20231218-010100.png…]()

**Comment by mischiefCloud** [comment]
![Screenshot_20231218-010100](https://github.com/yamin8000/freeDictionaryApp/assets/152065885/4264db19-6a56-4216-9411-8811f7e6eb3e)

**Comment by yamin8000** [comment]
> It is working, great job. Looks so much better on my phone, I appreciate it so much 💜

I'm glad you liked it.  
Thank you for your suggestion.
