### ISSUE TITLE
[Feature Request] Oled theme

### ISSUE THREAD

**Issue by Toiletmason** [yamin8000/freeDictionaryApp#54]
Would be a nice addition to the app.

**Comment by yamin8000** [comment]
> Would be a nice addition to the app.

https://github.com/yamin8000/freeDictionaryApp/releases/tag/1.5.7
Temporarily I added a oled theme that only is relative to the app's dark theme so if your system-wide theme is dark and app theme is set to system/dynamic then oled is not applied.

**Comment by Toiletmason** [comment]
I'm using oneui 5.1 android 13 and it is like you said. It doesn't work for me.

**Comment by yamin8000** [comment]
> I'm using oneui 5.1 android 13 and it is like you said. It doesn't work for me.

Did you changed the app's theme in the app settings?

**Comment by Toiletmason** [comment]
![Screenshot_20231226_171029_freeDictionary.jpg](https://github.com/yamin8000/freeDictionaryApp/assets/23698116/6994dd8c-3b91-4431-b654-7d51bf79e784)

**Comment by yamin8000** [comment]
> ![Screenshot_20231226_171029_freeDictionary.jpg](https://private-user-images.githubusercontent.com/23698116/292929120-6994dd8c-3b91-4431-b654-7d51bf79e784.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2NjM4MzAsIm5iZiI6MTcwMzY2MzUzMCwicGF0aCI6Ii8yMzY5ODExNi8yOTI5MjkxMjAtNjk5NGRkOGMtM2I5MS00NDMxLWI2NTQtN2Q1MWJmNzllNzg0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDA3NTIxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3NTFkZmRlNWQ2ZGE1NWQyMjdhZTQ3ODk2OGZmYWNjNGU4NmYyNTZjNzRmNTVmYzJjMTQ1OTY1MGFhYTdjNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xrXedVJaZVGXYid2D0VvbH2m6NUUm1FzJcHYWfPEazI)

Do you expect darker than this?

**Comment by Toiletmason** [comment]
An oled theme is generally #000000 black and uses a darker grey to show headers and stuff. I'll show you a screenshot of audile which is an open source music recognition app.
![Screenshot_20231227_015509_Audile.jpg](https://github.com/yamin8000/freeDictionaryApp/assets/23698116/3f0a1117-2358-49de-8c81-a433aa9f8aad)

**Comment by yamin8000** [comment]
> An oled theme is generally #000000 black and uses a darker grey to show headers and stuff. I'll show you a screenshot of audile which is an open source music recognition app. ![Screenshot_20231227_015509_Audile.jpg](https://private-user-images.githubusercontent.com/23698116/292986403-3f0a1117-2358-49de-8c81-a433aa9f8aad.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2NjQxMTgsIm5iZiI6MTcwMzY2MzgxOCwicGF0aCI6Ii8yMzY5ODExNi8yOTI5ODY0MDMtM2YwYTExMTctMjM1OC00OWRlLThjODEtYTQzM2FhOWY4YWFkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDA3NTY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1MDg1MmM2ZTMyOGM4OTkwZmJjODBmZGI4MDc0Yzc3NDIwZjNmNGQyMWE3ZGRiYTczZGI4OTNkNTE1NWY2NjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.izl4Pq8Q5VaZnQSZbgqtMW-ZSnPjMolQNPAGkHCu0sY)

OK, I'll reconsider this feature change.

**Comment by yamin8000** [comment]
@Toiletmason Did you try the [latest](https://github.com/yamin8000/freeDictionaryApp/releases/tag/1.5.8) version? I darkened the OLED theme more. Is that what you view as a genuine OLED theme?

**Comment by Toiletmason** [comment]
@yamin8000 Yes sir. There are a couple of things I might have done differently, but it's your app my man.
Maybe use some of the color you used for the icon and make some lines pop. Idk.

Great work and thanks for taking my input into consideration.

**Comment by Toiletmason** [comment]
@yamin8000 

After the update it seems like the background isn't truly black anymore. The borders look sick, but any chance you can make the background #000000 black? On oled screens the pixels emit no light.

**Comment by yamin8000** [comment]
> @yamin8000 
> 
> After the update it seems like the background isn't truly black anymore. The borders look sick, but any chance you can make the background #000000 black? On oled screens the pixels emit no light.

I didn't change the background for OLED in this version and it was never #000000 black in the first place.  
The OLED theme is still temporary in my view and even its implementation is buggy.  
Unfortunately I don't have an OLED device so it looks black enough to me.  
I'll work on it, I should set the background to pitch black manually.

**Comment by yamin8000** [comment]
> @yamin8000
> 
> After the update it seems like the background isn't truly black anymore. The borders look sick, but any chance you can make the background #000000 black? On oled screens the pixels emit no light.

https://github.com/yamin8000/freeDictionaryApp/releases/tag/1.5.91
