### ISSUE TITLE
F-Droid build not reproducible

### ISSUE THREAD

**Issue by linsui** [yamin8000/freeDictionaryApp#55]
[diff.zip](https://github.com/yamin8000/freeDictionaryApp/files/13779921/diff.zip)

**Comment by yamin8000** [comment]
> [diff.zip](https://github.com/yamin8000/freeDictionaryApp/files/13779921/diff.zip)

It's probably because I changed the release file after the release, it wasn't the same as the source code. I removed the 1.5.7 tag and made a new 1.5.7 release and I uploaded an apk equal to the source code, hope this will fix it.

**Comment by linsui** [comment]
Fixed, thanks!
